### ISSUE TITLE
윈도우 환경 yolov5 PosixPath 문제

### ISSUE THREAD

**Issue by corinB** [corinB/Opene#2]
PosixPath 는 리눅스,맥 환경에서 쓰임
윈도우 로컬에서 사용하려니까 안되서 

imprt pathlib
if sys.platform == "win32":
    temp = pathlib.PosixPath
    pathlib.PosixPath = pathlib.WindowsPath
    del temp

이거 임포트문 바로 밑에 추가
yolov5 공식 깃허브에서 해결될지는 모르지만 아직 검증된 방안이 아니라 비추천 한다고 하지만 다른 해결 방안이 없음
추후 push 한다면  mac, linux 환경에서는 
 yolov5/detect.py 에서 해강 코드 주석처리 해야함

**Comment by dabbun** [comment]
확인했숨

**Comment by dabbun** [comment]
잘못닫았숨.... 확인

**Comment by dabbun** [comment]
잘못닫았숨... 확인

**Comment by corinB** [comment]
해결 완료 진행 코드 상단 임포트문 바로 아래

import pathlib

temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

해당 코드 추가시 해결 완료, 단 리눅스, 맥은 해당 코드 제거해야함
